version: '3'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=miro
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    env_file:
      - .env
      - .version
    command: bash -c "gunicorn -c gunicorn.conf --log-level INFO --reload -b 0.0.0.0:8000 config.wsgi"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_READ_DOT_ENV_FILE=true
      - PGHOST=db
      - PYTHONDONTWRITEBYTECODE=true
{%- if cookiecutter.redis %}
  redis:
    image: "redis:alpine"
{%- endif -%}
{%- if cookiecutter.celery %}
  celery:
    build: .
    command: celery -A config worker -l debug
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_READ_DOT_ENV_FILE=true
      - PYTHONDONTWRITEBYTECODE=true
{% endif -%}

volumes:
  postgres_data:
